"""update supplyinfo with quantity

Revision ID: 55b5874f830d
Revises: e0ea2ac4ecba
Create Date: 2024-04-12 18:35:25.285093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b5874f830d'
down_revision = 'e0ea2ac4ecba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply_info', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
