"""add quantity to dishinfo

Revision ID: 97cab0de78b0
Revises: cfb8902fa6de
Create Date: 2024-04-14 20:38:25.074815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cab0de78b0'
down_revision = 'cfb8902fa6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish_information', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
