"""remove unnecessary fields

Revision ID: cfb8902fa6de
Revises: 55b5874f830d
Create Date: 2024-04-14 16:37:19.109096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb8902fa6de'
down_revision = '55b5874f830d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('card_number',
               existing_type=sa.VARCHAR(length=19),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('supply_order', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('card_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=19),
               existing_nullable=False)

    # ### end Alembic commands ###
